### PR TITLE
support pd.Series and pd.DataFrame in Client.write

### PR DESCRIPTION
**Pull request by briancappello**
Not sure if this is the best way to do this, or if it's even a desired feature, but I found it helpful :)

### CODE REVIEW

**Comment by umitanuki** [comment]
I think it is.

**Comment by briancappello** [comment]
While I was playing around with this some more, I'm wondering if the conversion to `np.recarray` is unnecessary? Seems like extra work.

(Also, of little importance to me personally, but converting `pd.Series` to `np.recarray` on 2.7 seems to cause this to blow up due to the array not being in contiguous memory. Meanwhile it works when you craft a custom write request directly from the arrays in the series. Interestingly this branch _does_ work on 3.6, so I'm not sure what's going on behind the scenes there. Same pandas/numpy versions.)

**Comment by umitanuki** [comment]
@briancappello what do you mean? You can get byte array directly from series/dataframe? If so yes it makes more sense to directly do so rather than getting recarray first.

**Comment by umitanuki** [comment]
This actually broke the test and README example. Let's fix that first.

**Comment by briancappello** [comment]
hey sorry for delayed response, working on this as we speak :)

here's where I'm at currently:

```
import numpy as np
import pandas as pd
import pymarketstore as pymkts
import six
import talib as ta

from pymarketstore.client import get_rpc_client

if six.PY2:
    memoryview = buffer


client = pymkts.Client()
rpc = get_rpc_client()(endpoint='http://localhost:5993/rpc')


def recarray_write_request(recarray, tbk, isvariablelength=False):
    return dict(
        dataset=dict(
            types=[recarray.dtype[name].str.replace('<', '')
                   for name in recarray.dtype.names],
            names=recarray.dtype.names,
            data=[bytes(memoryview(recarray[name]))
                  for name in recarray.dtype.names],
            length=len(recarray),
            startindex={tbk: 0},
            lengths={tbk: len(recarray)},
        ),
        is_variable_length=isvariablelength,
    )


def series_write_request(series, tbk, isvariablelength=False):
    epoch = series.index.to_numpy(dtype='i8') / 10**9
    return dict(
        dataset=dict(
            types=['i8', series.dtype.str.replace('<', '')],
            names=['Epoch', series.name or tbk.split('/')[-1]],
            data=[bytes(memoryview(epoch.astype('i8'))),
                  bytes(memoryview(series.to_numpy()))],
            length=len(series),
            startindex={tbk: 0},
            lengths={tbk: len(series)},
        ),
        is_variable_length=isvariablelength,
    )


def df_write_request(df, tbk, isvariablelength=False):
    epoch = df.index.to_numpy(dtype='i8') / 10 ** 9
    return dict(
        dataset=dict(
            types=['i8'] + [dtype.str.replace('<', '')
                            for dtype in df.dtypes],
            names=['Epoch'] + df.columns.to_list(),
            data=[bytes(memoryview(epoch.astype('i8')))] + [
                bytes(memoryview(df[name].to_numpy()))
                for name in df.columns
            ],
            length=len(df),
            startindex={tbk: 0},
            lengths={tbk: len(df)},
        ),
        is_variable_length=isvariablelength,
    )


def write(data, tbk, isvariablelength=False):
    if isinstance(data, np.recarray):
        write_request = recarray_write_request(data, tbk, isvariablelength)
    elif isinstance(data, pd.Series):
        write_request = series_write_request(data, tbk, isvariablelength)
    elif isinstance(data, pd.DataFrame):
        write_request = df_write_request(data, tbk, isvariablelength)
    else:
        raise Exception('unsupported data type: ', type(data))

    reply = rpc.call('DataService.Write', requests=[write_request])
    reply = rpc.codec.loads(reply.content, encoding='utf-8')
    resp = rpc.response(reply)
    return resp


if __name__ == '__main__':
    amd_prices = pymkts.Params('AMD', '1D', 'OHLCV')
    amd_ta = pymkts.Params('AMD', '1D', 'SMA200')

    amd = client.query(amd_prices).first().df()
    sma200 = ta.SMA(amd.Close, timeperiod=200)

    amd_recarray = amd.to_records(index_dtypes='i8')
    amd_recarray.Epoch = (amd_recarray.Epoch / 10**9).astype('i8')
    write(amd_recarray, 'AMD2/1D/OHLCV')
    amd2 = client.query(pymkts.Params('AMD2', '1D', 'OHLCV')).first().df()
    print(amd_recarray['Epoch'] == (amd2.index.to_numpy(dtype='i8') / 10**9).astype('i8'))
    print(amd_recarray['Close'] == amd2.Close.to_numpy())

    write(amd, amd_prices.tbk)  # df
    amd_df = client.query(amd_prices).first().df()
    print(amd.Close == amd_df.Close)

    write(sma200, amd_ta.tbk)   # series
    r = client.query(amd_ta).first().df()
    print(sma200.to_numpy() == r.SMA200.to_numpy())
```

However, I feel like I'm loosing my mind a bit because this time the call to `df.to_records` is blowing up on 2.7. Investigating...

**Comment by umitanuki** [comment]
OK. Let me know when it's ready. I think it's useful.

**Pull request merged**
