### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by dakimura**
see
https://github.com/alpacahq/marketstore/blob/master/frontend/write.go#L17

### CODE REVIEW

**Comment by bynr** [comment]
This is allowing to write ticks data with the python client! Great catch :1st_place_medal:

**Comment by umitanuki** [comment]
Please do not update the version string in an individual PR. Otherwise looks good.

**Comment by dakimura** [comment]
@umitanuki sorry! I reverted the version update.

**Comment by umitanuki** [comment]
Thanks

**Pull request merged**
